### ISSUE TITLE
artistの一番古い写真の読み込み

### ISSUE THREAD

**Issue by momohayashi** [ttoshiki/RinaYatera#11]

**Comment by momohayashi** [comment]
<img width="1043" alt="スクリーンショット 2019-12-12 10 21 57" src="https://user-images.githubusercontent.com/57060688/70674680-1b95e000-1cca-11ea-85ea-709f611944f6.png">

**Comment by momohayashi** [comment]
SSSIA

**Comment by ttoshiki** [comment]
これ枚数足りないからこうなってます
この辺で話していた23枚以上追加してもらえれば直ります
<img width="704" alt="スクリーンショット 2019-12-12 11 08 07" src="https://user-images.githubusercontent.com/48824550/70676496-b218d000-1ccf-11ea-8221-540d782605d4.png">

**Comment by momohayashi** [comment]
なるほど、理解しました。
すいません、ありがとうございます！
