### ISSUE TITLE
gallery＆worksページ/pcホバー時に『view more』の文字が下がる

### ISSUE THREAD

**Issue by momohayashi** [ttoshiki/RinaYatera#12]
該当サムネイルはgalleryとworksページ共々同じ位置です。

.photos.pc-img.lastを消すと解消されましたが、セクションの最下部のmarginが広がってしまいました。
でそれを解消しようと思って色々いじっては見たものの、
うまくいきませんでした。

もっと読み込むボタンを読み込むと、問題が解消されるのもちょっと原因がわからず、、、
納品後に申し訳ないですが、見てもらえると嬉しいです。

**Comment by momohayashi** [comment]
![スクリーンショット-2019-12-15-15 19 04](https://user-images.githubusercontent.com/57060688/70859048-92440f00-1f50-11ea-948a-6c815885fd0b.jpg)
<img width="505" alt="スクリーンショット 2019-12-12 10 08 45" src="https://user-images.githubusercontent.com/57060688/70859051-9cfea400-1f50-11ea-93a0-001856065172.png">

**Comment by momohayashi** [comment]
artistセクションでの動作確認をするためダミーを追加した関係で、現象がある画像の内容がずれました。
問題の箇所はPCでいうと一列目の左から４番目の画像になります。

**Comment by ttoshiki** [comment]
#15で直しました。こちらも確認していただいて大丈夫そうであればcloseをお願いします

**Comment by momohayashi** [comment]
確認しました。ご対応ありがとうございます！
