### ISSUE TITLE
SP/もっと読み込むボタンで出現した画像をタップした時、PCホバー時の「view more」が表示される

### ISSUE THREAD

**Issue by momohayashi** [ttoshiki/RinaYatera#13]
すいません、、、
見ていただけると幸いです。

**Comment by momohayashi** [comment]
<img width="148" alt="スクリーンショット 2019-12-15 15 57 02" src="https://user-images.githubusercontent.com/57060688/70859247-f3211680-1f53-11ea-86e5-284c0b90b25b.png">

**Comment by ttoshiki** [comment]
@momohayashi #14 で解決しました（本番にアップ済み）
確認してOKそうだったらcloseお願いします。

**Comment by momohayashi** [comment]
こちらも確認しました！！ありがとうございます。
