### ISSUE TITLE
SP/もっと読み込むボタンを押した後のモーダルがサムネイルになってる問題

### ISSUE THREAD

**Issue by momohayashi** [ttoshiki/RinaYatera#16]
<img width="370" alt="スクリーンショット 2019-12-17 1 10 19" src="https://user-images.githubusercontent.com/57060688/70922959-5ac98580-206a-11ea-8f91-a4685fa880b2.png">

ほんっっっとうに気づいておらずすいません、、、
こちらも見ていただけますでしょうか？？

よろしくお願いいたします、、、

**Comment by ttoshiki** [comment]
@momohayashi 多分これで良さそうなのでOKそうだったらcloseお願いします 🙏

**Comment by momohayashi** [comment]
確認しました。ありがとうございます！
