### ISSUE TITLE
pc/sp共通　worksモーダルの画面送りのバグ

### ISSUE THREAD

**Issue by momohayashi** [ttoshiki/RinaYatera#18]
![bug](https://user-images.githubusercontent.com/57060688/71359545-168d3680-25d0-11ea-87f5-c624af3174c2.jpg)
添付画像のようにモーダルの画面送りが順番通りに表示されません。
添付のパターンは1部のもので、検証するともっとパターンがありそうです。

galleryは問題なく回ってるので、挙動をgalleryに統一して頂けますと幸いです。
お手数ですが、ご確認くださいませ。

**Comment by momohayashi** [comment]
こちら最後のissueになるかと思います！どうぞよろしくお願いいたします！

**Comment by ttoshiki** [comment]
@momohayashi 直せたと思うので良さそうであればcloseお願いします 🙏

**Comment by momohayashi** [comment]
ご対応ありがとうございます！
モーダルの画像送りはよくなってますが、
galletyとworks共通で読み込んだ後のサムネイルの表示枚数がバグってるような、、、

**Comment by momohayashi** [comment]
<img width="1303" alt="スクリーンショット 2019-12-25 23 21 52" src="https://user-images.githubusercontent.com/57060688/71447045-69e8bb80-276d-11ea-9e44-5ea9de5b27c4.png">
otherとfamilyについては一回読み込むとこんなに写真一気に出てきましたっけ？

**Comment by ttoshiki** [comment]
@momohayashi すみませんーこれで大丈夫なはずです

**Comment by momohayashi** [comment]
@ttoshiki 
確認しました！
ご対応ありがとうございます。これでもう、バグ等ないと思います。

なんだかんだ足の長いプロジェクトになりましたね。お疲れ様でした！
closeします〜。
