### ISSUE TITLE
追加画像の4枚目までと5枚目から8枚目までのmarginの変更を行う

### ISSUE THREAD

**Issue by ttoshiki** [ttoshiki/RinaYatera#5]

**Comment by ttoshiki** [comment]
@momohayashi これGALLERYのなかのOTHER、WORKSの中のFAMILYはmargin変えなくて大丈夫そうですね。
GALLERYのARTISTとWORKSのWEDDINGの下の余白が狭い方が違和感あるのですが余白が違う理由はなんでしょうか？
GALLERYのARTISTとWORKSのWEDDINGを囲っている `photos-h2__parents` のmargin-bottomを削除すれば良さそう感あります（ちゃんと同じになるかはみてないです）

### Wedding
<img width="1096" alt="スクリーンショット 2019-12-11 21 19 03" src="https://user-images.githubusercontent.com/48824550/70621007-ebaff380-1c5b-11ea-86ec-00761e813981.png">


### Family
<img width="1105" alt="スクリーンショット 2019-12-11 21 19 14" src="https://user-images.githubusercontent.com/48824550/70621042-fa96a600-1c5b-11ea-88bc-86f935f4a9f9.png">

**Comment by ttoshiki** [comment]
htmlの方はlastっていうクラスを最後の4枚につけてますかね

**Comment by ttoshiki** [comment]
続けて見せたい感じですかね。なるほどー

**Comment by momohayashi** [comment]
<img width="785" alt="スクリーンショット 2019-12-11 23 15 20" src="https://user-images.githubusercontent.com/57060688/70628799-291c7d00-1c6c-11ea-9431-5559bebeee80.png">

**Comment by momohayashi** [comment]
ですです。

同じくらい開けると間延びしてしまう、みるテンポが狂うので
指摘貰った所は二つのマージントップ合わせて他の余白と同じ様にしたかった、、、、

ですがちょっとartistとweddingの下の余白が、familyと比べて広いので
違和感を感じられたのだと思います。

ぶっちゃけ、余白の違い気づいたの最近でしたw
作ってる当時気づきませんでした。

**Comment by momohayashi** [comment]
こっちの不備なんで、私直した方がいい気もしますが、どうしましょうか？

**Comment by momohayashi** [comment]
別のissueで書きましたけど、十分すぎるほどご対応いただいたので
cssでできることはこっちでやろうかと。

ご確認のほどよろしくお願いいたします。

**Comment by ttoshiki** [comment]
とりあえず今htmlに合わせて直してみたのでマージしますね

**Comment by momohayashi** [comment]
ありがとうございます！

えと、otherとfamilyのもっと読み込むボタンを押すと
artistとweddingの余白が広がってしまってますー。

**Comment by ttoshiki** [comment]
あーなるほど。
明日以降直します！

**Comment by momohayashi** [comment]
すいません、ありがとうございます！

**Comment by ttoshiki** [comment]
@momohayashi 直しました！

**Comment by momohayashi** [comment]
<img width="975" alt="スクリーンショット 2019-12-12 9 58 29" src="https://user-images.githubusercontent.com/57060688/70673445-f99a5e80-1cc5-11ea-8122-276b66952bb1.png">

**Comment by momohayashi** [comment]
@ttoshiki 
ありがとうございます！
何度もすいません、、、worksのボタンを2回押した後の余白が広いままになってます、、、

**Comment by momohayashi** [comment]
<img width="300" alt="スクリーンショット 2019-12-12 9 57 18" src="https://user-images.githubusercontent.com/57060688/70673524-3a927300-1cc6-11ea-926b-1a7187b19d38.png">

**Comment by momohayashi** [comment]
galleyのartist,一回読み込むとボタンと画像の余白がこんな感じに、、、

**Comment by momohayashi** [comment]
<img width="247" alt="スクリーンショット 2019-12-12 10 05 28" src="https://user-images.githubusercontent.com/57060688/70673732-f3f14880-1cc6-11ea-99b8-9f5133429dbc.png">
つづけてすいません、、、
こちらも、、、この写真だけホバー時の「view more」だけ下がってるのってなんでなんでしょうか？機能的なもの絡んでないのなら、こちらで修正します。

**Comment by ttoshiki** [comment]
>何度もすいません、、、worksのボタンを2回押した後の余白が広いままになってます、、、

これはworksの枚数が2回目読み込みの時5枚しかないからです。
あと3枚追加してもらえれば正常な余白になるはずです。
artistも同様に枚数が少ないからです。

**Comment by ttoshiki** [comment]
>この写真だけホバー時の「view more」だけ下がってるのってなんでなんでしょうか？機能的なもの絡んでないのなら、こちらで修正します。

これもcss的な問題ですね...
直せそうですか？
lastのclassがついている時にview moreも位置が変わってしまうのが原因です。

**Comment by momohayashi** [comment]
すいません、テストしずらかったですよね。
諸々承知しました。
ホバー時のずれはこちらでやってみます。
