### ISSUE TITLE
MORE LOAD時のアニメーションの調整

### ISSUE THREAD

**Issue by ttoshiki** [ttoshiki/RinaYatera#6]

**Comment by ttoshiki** [comment]
@momohayashi これかなり頑張ってやってみましたが、一瞬ガクッとなる動作を消すのは無理そうです。
理由としてはdisplay: flexで4列にしているので
- ボタンが消える
- 消えた分だけ広がる←この動作がどうしても一瞬入る
- 画像が入ってきて4列になる

これを改善するには `display: grid` などで3列になっても崩れないようなスタイルにするという方法しか今のところ考えられません。
さすがにdisplay: gridにするのはスコープ外なのでこれでお願いしたいのですがどうでしょうか。

**Comment by momohayashi** [comment]
承知しました！
色々試していただき、本当に本当にありがとうございます。

もう一個のissueもこっちでできそうならやっちゃいますので
プロジェクト完了ですかねー。
他、田丸先生がやんなきゃいけないissueないですよね？

**Comment by ttoshiki** [comment]
ありがとうございます 🙇‍♂️🙇‍♂️🙇‍♂️
そうですね！多分大丈夫だと思うのですが林さんの方で実装に不備がないか確認お願いしていいですか？

**Comment by ttoshiki** [comment]
こちらはcloseしますね

**Comment by momohayashi** [comment]
こちらのコメント気づきませんでした。
余白の調整していただいたあと、改めて確認させてもらいますね！

あと少し、懲りずにどうぞよろしくお願いいたします！
では別issueで〜
