### ISSUE TITLE
gallery＆worksページにlazy_loadかけてみる

### ISSUE THREAD

**Issue by momohayashi** [ttoshiki/RinaYatera#8]

**Comment by momohayashi** [comment]
@ttoshiki 
デジハリスラッグのweb-design-trendsに載っけてた↓記事
https://note.com/rdlabo/n/n8731adda8b57#jiV0F

読んだんですが、lazy_loadかけても意味ないってことでしょうか？？

**Comment by ttoshiki** [comment]
というよりdefaultでlazyの挙動になっているというのが正しいですかね。
以下記事の方が詳細書いてあります。
https://qiita.com/spaceonly/items/9d9b3fe46e43524a535a

**Comment by momohayashi** [comment]
これは読みました〜。でもクロームのみですよね？
別のブラウザでは挙動が違うってことですか？

**Comment by ttoshiki** [comment]
その可能性はありますね。
やってみる価値はあると思いますが劇的には変わらないかもしれませんね

**Comment by momohayashi** [comment]
うーん、、なるほど。
優先順位低い作業ってことですね。ありがとうございます！！
